version: '3'

services:
    registry:
        image: registry:2.6.1
        container_name: registry
        restart: always
        ports:
            - "5050:5000"
        networks:
            - nginx-proxy

networks:
    nginx-proxy:
        external:
            name: nginx-proxy
