version: '3'

services:
    jenkins:
        build: .
        container_name: jenkins
        restart: always
        ports:
            - "8080:8080"
            - "5000:5000"
        environment:
            VIRTUAL_HOST: jenkins.local
            VIRTUAL_PORT: 8080
        volumes:
            - jenkins_data:/var/jenkins_home
            - /var/run/docker.sock:/var/run/docker.sock
        networks:
            - nginx-proxy

    jenkins-nginx-webhook-proxy:
        image: nginx:1.12.0
        container_name: jekins-nginx-webhook-proxy
        restart: always
        ports:
            - "9000:80"
        volumes:
            - ./conf/nginx/conf.d:/etc/nginx/conf.d
        networks:
            - nginx-proxy

volumes:
    jenkins_data:

networks:
    nginx-proxy:
        external:
            name: nginx-proxy
