version: '3'
services:
    openvpn:
        image: kylemanna/openvpn:2.4
        container_name: openvpn
        ports:
            - "1194:1194/udp"
        restart: always
        cap_add:
            - NET_ADMIN
        volumes:
            - ./conf:/etc/openvpn
